# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0002_auto_20180426_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u53d1\u5e03\u8005'),
        ),
    ]
