# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20180426_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(default='img/default_middile_2.png', upload_to='images/%Y_%m', verbose_name='\u5546\u54c1\u5b9e\u4f53\u56fe\u7247'),
        ),
    ]
