# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-29 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20180426_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.IntegerField(choices=[(1, '\u4e66\u7c4d\u7c7b'), (2, '\u673a\u52a8\u7c7b'), (3, '\u7535\u5b50\u4ea7\u54c1'), (4, '\u5176\u4ed6')], default=1, verbose_name='\u5546\u54c1\u5206\u7c7b'),
        ),
    ]
