# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.CharField(max_length=20, verbose_name='\u5b66\u53f7')),
                ('grade', models.CharField(max_length=50, verbose_name='\u73ed\u7ea7')),
                ('username', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u53ef\u6ce8\u518c\u5b66\u751f\u4fe1\u606f',
                'verbose_name_plural': '\u53ef\u6ce8\u518c\u5b66\u751f\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='emailverifyrecord',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
    ]
