# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-26 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180426_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractive',
            name='active',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u5df2\u7ecf\u6ce8\u518c'),
        ),
    ]
