# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-28 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=50, verbose_name='\u9a8c\u8bc1\u7801'),
        ),
    ]
