# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180428_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='img/default_middile_2.png', upload_to='imagepersonal/%Y_%m'),
        ),
    ]
